# 1. Array Creation & Basics

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [3]:
b = np.arange(1, 11, 2)       # [1,3,5,7,9]
b

array([1, 3, 5, 7, 9])

In [4]:
c = np.linspace(0, 1, 5)      # 5 values from 0 to 1
c

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [5]:
d = np.zeros((2,3))           # 2x3 matrix of zeros
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
e = np.ones((3,3))            # 3x3 matrix of ones
e

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
f = np.eye(4)                 # 4x4 Identity matrix
f

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 2. Array Properties

In [8]:
arr = np.array([[1,2,3],[4,5,6]])

In [9]:
print(arr.shape)   # (2,3)

(2, 3)


In [10]:
print(arr.ndim)    # 2 (dimensions)

2


In [11]:
print(arr.size)    # 6 (total elements)

6


In [12]:
print(arr.dtype)   # int64 (depends on system)

int32


# 3. Array Indexing & Slicing

In [13]:
arr = np.arange(10)   # [0 1 2 3 4 5 6 7 8 9]

In [14]:
print(arr[2:7])       # [2 3 4 5 6]

[2 3 4 5 6]


In [15]:
print(arr[::-1])      # Reverse array

[9 8 7 6 5 4 3 2 1 0]


# 4. Reshape & Flatten

In [16]:
a = np.arange(12)      

In [17]:
print(a.reshape(3,4))   # Reshape to 3x4

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
print(a.flatten())      # Convert to 1D

[ 0  1  2  3  4  5  6  7  8  9 10 11]


# 5. Random Numbers

In [19]:
np.random.rand(3,2)      # Uniform [0,1)

array([[0.62551799, 0.55520902],
       [0.47386215, 0.08198903],
       [0.66754395, 0.09874489]])

In [20]:
np.random.randn(3,2)     # Normal distribution

array([[0.91020861, 0.1289199 ],
       [1.53469323, 1.21899982],
       [0.5996922 , 0.52273247]])

In [21]:
np.random.randint(1,10,5) # 5 random ints between 1-9

array([9, 3, 9, 3, 5])

# 6. Mathematical Operations

In [22]:
arr = np.array([1,2,3,4,5])
print(np.sum(arr))   # 15
print(np.min(arr))   # 1
print(np.max(arr))   # 5
print(np.std(arr))   # Standard deviation
print(np.var(arr))   # Variance

15
1
5
1.4142135623730951
2.0


# 8. Sorting & Unique

In [23]:
arr = np.array([3,1,2,1,4,3])

In [24]:
print(np.sort(arr))     # [1 1 2 3 3 4]

[1 1 2 3 3 4]


In [25]:
print(np.unique(arr))   # [1 2 3 4]

[1 2 3 4]


# 9. Boolean Indexing & Masking

In [26]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 25])   # [30 40 50]

[30 40 50]


# 10. Matrix Operations

In [27]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [28]:
print(np.add(A,B))         # Element-wise addition

[[ 6  8]
 [10 12]]


In [29]:
print(np.matmul(A,B))      # Matrix multiplication

[[19 22]
 [43 50]]


In [30]:
print(np.linalg.inv(A))    # Inverse of matrix

[[-2.   1. ]
 [ 1.5 -0.5]]


In [31]:
print(np.linalg.det(A))    # Determinant

-2.0000000000000004


In [32]:
print(np.linalg.eig(A))    # Eigenvalues & vectors

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
