# Numpy : Numeric Python

In [1]:
import numpy as np

In [2]:
list1=[12,34,56,78,90]
print(list1)

[12, 34, 56, 78, 90]


In [3]:
ar1=np.array([[12,4,56,78,90,54,34,45],[12,4,56,78,90,54,34,45]]) # Each inner list ([12,4,56,...,45]) becomes one row in the array.
print(ar1) # 2 rows and 8 columns

[[12  4 56 78 90 54 34 45]
 [12  4 56 78 90 54 34 45]]


In [4]:
print(type(ar1))

<class 'numpy.ndarray'>


In [5]:
print(ar1.shape)

(2, 8)


In [6]:
print(ar1.dtype)

int32


In [7]:
print(ar1.T) # .T gives the transpose of the array: where rows become columns and columns become rows.
# So the shape changes to (8, 2) → 8 rows × 2 columns.

[[12 12]
 [ 4  4]
 [56 56]
 [78 78]
 [90 90]
 [54 54]
 [34 34]
 [45 45]]


In [8]:
num1=num1=np.array([[23,45,67],[12,34,78]])

In [9]:
num2=np.array([[5,5,5],[3,3,3]])

In [10]:
print(np.add(num1,num2))

[[28 50 72]
 [15 37 81]]


In [11]:
print(np.subtract(num1,num2))

[[18 40 62]
 [ 9 31 75]]


In [12]:
print(np.multiply(num1,num2))

[[115 225 335]
 [ 36 102 234]]


In [13]:
print(np.divide(num1,num2))

[[ 4.6         9.         13.4       ]
 [ 4.         11.33333333 26.        ]]


In [14]:
print(np.power(num1,num2))

[[   6436343  184528125 1350125107]
 [      1728      39304     474552]]


In [15]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

# Function Parameter

In [16]:
# Positional Parameter
def demo(name,age,location="Delhi"):
    print("Name is",name)
    print("Age is ",age)
    print("Location is ",location)

In [17]:
demo("Rahul",34,"Pune")

Name is Rahul
Age is  34
Location is  Pune


In [18]:
demo("Pune",34,"Rahul") # if data is given in wrong position we will get wrong answer

Name is Pune
Age is  34
Location is  Rahul


In [19]:
# Keyword = Argument: We can shuffle arguments with keyword
demo(location="dadar",name="Rahul",age=34)

Name is Rahul
Age is  34
Location is  dadar


In [20]:
# Default parameter
demo("Priya",45) # if location is not given it takes default value of location from function definition

Name is Priya
Age is  45
Location is  Delhi


In [21]:
demo("anjali ",45,"Luknow")

Name is anjali 
Age is  45
Location is  Luknow


In [22]:
demo("pooja",45)

Name is pooja
Age is  45
Location is  Delhi


# Calendar

In [23]:
import calendar

In [24]:
dir(calendar)

['APRIL',
 'AUGUST',
 'Calendar',
 'DECEMBER',
 'Day',
 'EPOCH',
 'FEBRUARY',
 'FRIDAY',
 'HTMLCalendar',
 'IllegalMonthError',
 'IllegalWeekdayError',
 'IntEnum',
 'JANUARY',
 'JULY',
 'JUNE',
 'LocaleHTMLCalendar',
 'LocaleTextCalendar',
 'MARCH',
 'MAY',
 'MONDAY',
 'Month',
 'NOVEMBER',
 'OCTOBER',
 'SATURDAY',
 'SEPTEMBER',
 'SUNDAY',
 'THURSDAY',
 'TUESDAY',
 'TextCalendar',
 'WEDNESDAY',
 '_EPOCH_ORD',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_colwidth',
 '_get_default_locale',
 '_locale',
 '_localized_day',
 '_localized_month',
 '_monthlen',
 '_nextmonth',
 '_prevmonth',
 '_spacing',
 'c',
 'calendar',
 'datetime',
 'day_abbr',
 'day_name',
 'different_locale',
 'error',
 'firstweekday',
 'format',
 'formatstring',
 'global_enum',
 'isleap',
 'leapdays',
 'main',
 'mdays',
 'month',
 'month_abbr',
 'month_name',
 'monthcalendar',
 'monthrange',
 'prcal',
 'prmonth',
 'prweek',

In [25]:
print("Calendar of the year 2025 is : ")
print (calendar.calendar(2025,1,1,5,4)) # w,l,c,m, 10: distance between 2 months
# Return a m-column calendar for an entire year as a multi-line string.
# Optional parameters w, l, and c are for date column width, lines per week, and number of spaces between month columns, respectively.
# Try changing w l c m values
# The w parameter sets the date column width, l is the number of lines per week,
# c sets the spacing between month columns, and m is the number of month columns.

Calendar of the year 2025 is : 
                                              2025

      January                  February                  March                    April
Mo Tu We Th Fr Sa Su     Mo Tu We Th Fr Sa Su     Mo Tu We Th Fr Sa Su     Mo Tu We Th Fr Sa Su
       1  2  3  4  5                     1  2                     1  2         1  2  3  4  5  6
 6  7  8  9 10 11 12      3  4  5  6  7  8  9      3  4  5  6  7  8  9      7  8  9 10 11 12 13
13 14 15 16 17 18 19     10 11 12 13 14 15 16     10 11 12 13 14 15 16     14 15 16 17 18 19 20
20 21 22 23 24 25 26     17 18 19 20 21 22 23     17 18 19 20 21 22 23     21 22 23 24 25 26 27
27 28 29 30 31           24 25 26 27 28           24 25 26 27 28 29 30     28 29 30
                                                  31

        May                      June                     July                    August
Mo Tu We Th Fr Sa Su     Mo Tu We Th Fr Sa Su     Mo Tu We Th Fr Sa Su     Mo Tu We Th Fr Sa Su
          1  2  3  4     

In [26]:
print ("The Jan month of 2025 is : ") # print calendar of specific month
print(calendar.month(2025,1,2,1)) # Year,Month,2,1 are the spacings

The Jan month of 2025 is : 
    January 2025
Mo Tu We Th Fr Sa Su
       1  2  3  4  5
 6  7  8  9 10 11 12
13 14 15 16 17 18 19
20 21 22 23 24 25 26
27 28 29 30 31



In [27]:
calendar.monthcalendar(2025,9) # day wise for dec 2028, Mon to Sunday

[[1, 2, 3, 4, 5, 6, 7],
 [8, 9, 10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19, 20, 21],
 [22, 23, 24, 25, 26, 27, 28],
 [29, 30, 0, 0, 0, 0, 0]]

In [28]:
calendar.isleap(2024) # check leap year or not

True

In [29]:
# datetime module

In [30]:
from datetime import date # date related functions

In [31]:
today = date.today()
print("Today's date is: ",today)

Today's date is:  2025-09-12


In [32]:
# Current date in different formats
# dd/mm/YY
d1 = today.strftime("%d/%m/%Y") # dd/mm/yyyy 27/08/2024
print("d1 =", d1)

# Textual month, day and year
d2 = today.strftime("%B %d, %Y") # August 27, 2024, %B-Full month name, %Y-yyyy, %y-yy
print("d2 =", d2)

# mm/dd/yy
d3 = today.strftime("%m/%d/%y") # mm/dd/yy 08/27/24
print("d3 =", d3)

# Month abbreviation, day and year
d4 = today.strftime("%b-%d-%Y") # Dec-15-2023, %b-abb. of monthname
print("d4 =", d4)

d1 = 12/09/2025
d2 = September 12, 2025
d3 = 09/12/25
d4 = Sep-12-2025


In [33]:
from datetime import datetime # date and time related functions
now = datetime.now()

print("now =", now)

# dd/mm/YY H:M:S
dt_string = now.strftime("%d/%m/%Y %H:%M:%S")
print("date and time =", dt_string)

now = 2025-09-12 13:16:27.445817
date and time = 12/09/2025 13:16:27


In [34]:
import datetime

In [35]:
x = datetime.datetime.now()
print(x)

2025-09-12 13:16:27.465900


In [36]:
print(x.year)

2025


In [37]:
print(x.month)

9


In [38]:
print(x.strftime("%b")) #strftime: string formatted time
# https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes

Sep


In [39]:
print(x.strftime("%B"))

September


In [40]:
print(x.strftime("%d-%b-%Y"))

12-Sep-2025


In [41]:
# Date
#You can find difference between 2 dates

In [42]:
from datetime import date

In [43]:
print("Today's date: ",date.today())

Today's date:  2025-09-12


In [44]:
date1 = date(2020,2,25)
date2 = date(2023,12,14)

In [45]:
type(date1)

datetime.date

In [46]:
diff = date2 - date1

In [47]:
type(diff) # after subtraction we get a new data type as timedelta

datetime.timedelta

In [48]:
diff

datetime.timedelta(days=1388)

In [49]:
diff.days

1388

In [50]:
(date2 - date1).days

1388